services:
  complai:
    build: .
    container_name: complai_app

    ports:
      - "8501:8501"

    volumes:
      # ONLY logs (your rule)
      - ./logs:/app/logs

      # ML CHECKPOINTS
      - /home/chatziko/PycharmProjects/PythonProject/checkpoints:/app/checkpoints

      # CELEBA DATASET
      - /home/chatziko/PycharmProjects/PythonProject/celeba:/app/celeba

      # MALWARE DATASET
      - /home/chatziko/PycharmProjects/PythonProject/malware_bazaar_binaries:/app/malware_bazaar_binaries

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - PYTHONUNBUFFERED=1

    restart: unless-stopped