services:
  complai:
    build: .
    container_name: complai_app
    stdin_open: true
    tty: true



    ports:
      - "8502:8502"

    volumes:
      # ONLY logs (your rule)
      - ./logs:/app/logs

      # ML CHECKPOINTS
      - /home/chatziko/PycharmProjects/PythonProject/checkpoints/:/app/checkpoints/

      # CELEBA DATASET
      - /home/chatziko/PycharmProjects/PythonProject/celeba/:/app/celeba/

      # MALWARE DATASET
      - /home/chatziko/PycharmProjects/PythonProject/malware_bazaar_binaries/:/app/malware_bazaar_binaries/

     # HF home
      - /home/chatziko/.cache/huggingface:/app/cache/hf
      - /root/.cache/complai:/app/complai_cache


    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

    env_file:
      - .env
    environment:
      HF_HOME: /app/cache/hf
      NVIDIA_VISIBLE_DEVICES: all
      PYTHONUNBUFFERED: "1"
      HF_TOKEN: ${HF_TOKEN}
      INSPECT_ALLOW_UNSAFE_PATHS: "1"




    restart: unless-stopped
